name: azure-synapse-cicd-northwind

on:
  workflow_dispatch:
  push:
    branches:
      - workspace_publish

permissions:
  id-token: write
  contents: read

jobs:
  deploy_synapse_prod:
    name: Deploy Synapse to PROD (ARM + OIDC)
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del branch workspace_publish (donde está TemplateForWorkspace.json)
      - name: Checkout workspace_publish (Synapse publish artifacts)
        uses: actions/checkout@v4
        with:
          ref: workspace_publish

      # 2) Login a Azure con OIDC (igual que tu ADF)
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3) Deploy ARM template a tu Resource Group PROD
      - name: Deploy Synapse ARM to PROD
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: GR-PROD-NORTHWIND
          template: devsynapsenorthwind/TemplateForWorkspace.json
          parameters: devsynapsenorthwind/TemplateParametersForWorkspace.json
          # overrides tipo ADF (clave=valor). OJO: en arm-deploy se usa key=value (no -param "valor")
          overrideParameters: >
            workspaceName=prodsynapsenorthwind
            LS_adsl_sink_properties_typeProperties_url=https://adlsprodnorthwind.dfs.core.windows.net/
            devsynapsenorthwind-WorkspaceDefaultStorage_properties_typeProperties_url=https://adlsprodnorthwind.dfs.core.windows.net
            KeyVault_LS_properties_typeProperties_baseUrl=https://prodonpremisenorthwind.vault.azure.net/
            devsynapsenorthwind-WorkspaceDefaultSqlServer_connectionString=Integrated Security=False;Encrypt=True;Connection Timeout=30;Data Source=tcp:prodsynapsenorthwind.sql.azuresynapse.net,1433;Initial Catalog=master
