name: azure-adf-cicd-northwind

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install ADF Utilities package
        run: npm install
        working-directory: ${{ github.workspace }}/built/adf_package

      - name: Validate ADF DEV resources
        run: >
          npm run build validate
          ${{ github.workspace }}/
          /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/GR-DEV-NORTHWIND/providers/Microsoft.DataFactory/factories/adfdevanorthwind
        working-directory: ${{ github.workspace }}/built/adf_package

      - name: Export ARM template from ADF DEV
        run: >
          npm run build export
          ${{ github.workspace }}/
          /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/GR-DEV-NORTHWIND/providers/Microsoft.DataFactory/factories/adfdevanorthwind
          ExportedArmTemplate
        working-directory: ${{ github.workspace }}/built/adf_package

      - name: Upload ARM template artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ${{ github.workspace }}/built/adf_package/ExportedArmTemplate

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download ARM template artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate

      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy ARM to ADF PROD
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: GR-PROD-NORTHWIND
          dataFactoryName: adfprodnorthwind
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
          # ✅ OVERRIDES para PROD (lo que en DEV apunta a DEV, acá se reemplaza a PROD)
          #additionalParameters: >
          #  factoryName=adfprodnorthwind
          #  LS_adsl_prime_sink_DEV_properties_typeProperties_url=https://adlsprodprime.dfs.core.windows.net/
          #  LS_adsl_prime_sink_DEV_accountKey=${{ secrets.ADLS_PROD_ACCOUNT_KEY }}
