name: synapse-cicd-northwind

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_synapse_prod:
    name: Deploy Synapse to PROD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workspace_publish (Synapse publish artifacts)
        uses: actions/checkout@v4
        with:
          ref: workspace_publish

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Synapse workspace artifacts to PROD
        uses: Azure/Synapse-workspace-deployment@V1.9.1
        with:
          # TARGET (PROD)
          TargetWorkspaceName: "prodsynapsenorthwind"
          ResourceGroupName: "GR-PROD-NORTHWIND"

          # SOURCE templates (from workspace_publish branch)
          TemplateFile: "devsynapsenorthwind/TemplateForWorkspace.json"
          ParametersFile: "devsynapsenorthwind/TemplateParametersForWorkspace.json"

          # IMPORTANT: override DEV params to PROD values
          OverrideArmParameters: >
            -workspaceName "prodsynapsenorthwind"
            -LS_adsl_sink_accountKey "${{ secrets.PROD_ADLS_ACCOUNT_KEY }}"
            -KeyVault_LS_properties_typeProperties_baseUrl "https://prodonpremisenorthwind.vault.azure.net/"
            -LS_adsl_sink_properties_typeProperties_url "https://adslprodnorthwind.dfs.core.windows.net/"
            -devsynapsenorthwind-WorkspaceDefaultStorage_properties_typeProperties_url "https://adslprodnorthwind.dfs.core.windows.net"
            -devsynapsenorthwind-WorkspaceDefaultSqlServer_connectionString "Integrated Security=False;Encrypt=True;Connection Timeout=30;Data Source=tcp:prodsynapsenorthwind.sql.azuresynapse.net,1433;Initial Catalog=@{linkedService().DBName}"
            -LS_sql_source_properties_typeProperties_server "WIN-LB6LIL0FQ67,1433"
            -LS_sql_source_properties_typeProperties_database "NORTHWND"
            -LS_sql_source_properties_typeProperties_userName "onpremnorthwind"
