name: synapse-cicd-northwind

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Entorno destino"
        required: true
        default: "prod"
        type: choice
        options:
          - dev
          - prod
      sourceBranch:
        description: "Rama fuente (artefactos publicados)"
        required: true
        default: "workspace_publish"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-synapse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (artefactos publicados)
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sourceBranch }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set variables by ENV
        id: vars
        shell: bash
        run: |
          if [ "${{ inputs.env }}" = "dev" ]; then
            echo "WORKSPACE=devsynapsenorthwind" >> $GITHUB_OUTPUT
            echo "RG=GR-DEV-NORTHWIND" >> $GITHUB_OUTPUT
            echo "FOLDER=devsynapsenorthwind" >> $GITHUB_OUTPUT
          else
            echo "WORKSPACE=prodsynapsenorthwind" >> $GITHUB_OUTPUT
            echo "RG=GR-PROD-NORTHWIND" >> $GITHUB_OUTPUT
            # carpeta donde Synapse publica los ARM templates en workspace_publish (normalmente el nombre del DEV)
            echo "FOLDER=devsynapsenorthwind" >> $GITHUB_OUTPUT
          fi

      - name: Deploy Synapse Workspace Artifacts
        uses: Azure/Synapse-workspace-deployment@V1.9.1
        with:
          TargetWorkspaceName: ${{ steps.vars.outputs.WORKSPACE }}
          resourceGroupName: ${{ steps.vars.outputs.RG }}
          TemplateFile: ${{ steps.vars.outputs.FOLDER }}/TemplateForWorkspace.json
          ParametersFile: ${{ steps.vars.outputs.FOLDER }}/TemplateParametersForWorkspace.json
          operation: deploy
          FailOnMissingOverrides: false
